# Generated by Django 5.0.4 on 2024-10-03 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0002_borrow_borrow_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='balance_after_return',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
