# Generated by Django 5.0.4 on 2024-10-04 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_rating_book_reviews_count'),
        ('borrow', '0003_borrow_balance_after_return'),
        ('user_account', '0003_alter_useraccount_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='book.book'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowers', to='user_account.useraccount'),
        ),
    ]
