# Generated by Django 5.0.4 on 2024-10-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='book',
            name='reviews_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
